name: project_places_api_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.1
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
  flutter_screenutil: ^3.1.0
  image_picker: ^0.6.7+11
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  flutter_svg: ^0.19.1
  flutter_auth_buttons: ^0.10.0
  flutter_firebase_iid: ^0.0.1
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.1+2
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^2.0.0+1
  firebase_in_app_messaging: "^0.2.0+3"
  cloud_firestore: "^0.14.1+3"
  cloud_functions: "^0.7.0-dev.2"
  firebase_storage: "^5.0.0-dev.3"
  google_sign_in: ^4.5.3
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  json_annotation: ^3.0.0
  json_serializable: ^3.5.0
  shared_preferences: ^0.5.12
  unicode: ^0.2.4
  device_id: ^0.1.3
  
  google_fonts: ^1.1.0
  tiengviet: ^0.4.1
  mvp_core: ^0.0.3
  progress_dialog: ^1.2.4
  google_maps_flutter: ^1.0.1
  dio: ^3.0.10  
  carousel_slider: ^2.3.1

  smooth_star_rating: ^1.1.1
  tuple: ^1.0.3
  url_launcher: ^5.7.5
  multiselect_formfield: ^0.1.4
  flutter_rating_bar: ^3.0.1+1
  fl_chart: ^0.12.0
  group_radio_button: ^1.0.1
  geolocator: ^5.3.1
  #mapper: ^0.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.16.1

  
  build_runner: ^1.0.0
  
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher/res/mipmap-xhdpi/ic_launcher.png"

flutter_launcher_name:
  name: "Places Information"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/
    # - assets/launcher/icon_app.png
    - map.json
    - sad.png
    - passioMarkerDesign.png
    - 7ElevenMarkerDesign.png
    - donalMarkerDesign.png
    - starbucksMarkerDesign.png
    - tpBankMarkerDesign.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: lib\shared\fonts\Raleway-Regular.ttf
        - asset: lib\shared\fonts\Raleway-Bold.ttf
          weight: 700
        - asset: lib\shared\fonts\Raleway-LightItalic.ttf
          weight: 300
          style: italic
    - family: Roboto
      fonts:
        - asset: lib\shared\fonts\Roboto-Regular.ttf
    - family: CormorantGaramond
      fonts:
        - asset: lib\shared\fonts\CormorantGaramond-Regular.ttf
    - family: Playball
      fonts:
        - asset: lib\shared\fonts\Playball-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
